Removing unused variable warnings
flav1972/ArduinoINA219 pull request #4
Opened 2019-02-12 23:22 UTC by ulysse314

Hello,

This commit reduces the number of unused variable warnings.

Thanks,

2019-02-13 20:23 UTC, flav1972 requested changes
can you please put the declaration of variables block at the beginning of the method ?

2019-02-13 20:23 UTC, flav1972 commented on INA219.cpp
> -#if (INA219_DEBUG == 1)
Could you put all the variables definitions here ? It looks more like classic C style.

2019-02-14 22:02 UTC, ulysse314 commented
Done

2019-02-14 22:08 UTC, ulysse314 commented
I'm not convinced about moving the variables at the beginning of the method since it is c++, and not c. Also I feel it is better to have the variables next to the code, since it seems easier to read with one debug block.

2019-02-16 19:25 UTC, flav1972 approved these changes

2019-02-16 19:25 UTC, merged